function initLog( fname, expname, inc_ref_thr, inc_tra_thr, bpm1_thr, bpm2_thr,deltaTime_spike,deltaTime_beam_lost )
%   initLog.m creates the first part of the log file for the current
%   analysis run. Parameters are also saved
%
%   Inputs:
%     - fname: enter the full path ending with extension
%     - expname: the name of the file without extensions (e.g. Exp_full_3)
%     - vaious parameters of the analysis defined on top 
%     
%   Last modified: 26.08.2016 by Eugenio Senes

logID = fopen(fname, 'w+' ); 
msg1 = ['Analysis log for the file ' expname '.mat' '\n' ...
'Created: ' datestr(datetime('now')) '\n \n' ...
'User defined tresholds: \n' ...
'METRIC: \n' ...
'- inc_ref_thr: %3.2f \n' ... 
'- inc_tra_thr: %3.2f \n' ... 
'BPM charge' '\n' ...
'- bpm1_thr: %3.2f' '\n' ...
'- bpm2_thr: %3.2f' '\n' ...
'Time window for clusters ' '\n' ...
'- deltaTime_spike: %3.2f' '\n' ...
'- deltaTime_bem_lost: %3.2f' '\n' ...
'\n'];
fprintf(logID,msg1,inc_ref_thr, inc_tra_thr, bpm1_thr, bpm2_thr,deltaTime_spike,deltaTime_beam_lost);
fclose(logID);

end

