function [ texID ] = addPlotTex( datapath_write, name, pathName, extension )
% add a plot

texID = fopen([datapath_write filesep name '.tex'], 'a' ); 
cmd = ['\n' ...
'\\begin{landscape}' '\n' ...
'\\begin{center}' '\n' ...
'\\includegraphics[width = 28cm , keepaspectratio]{' pathName '.' extension '}' '\n' ...
'\\end{center}' '\n' ...
'\\end{landscape}' '\n' ...
'\\newpage' '\n' ...
'\n' ...
];
fprintf(texID,cmd);
fclose(texID);

end

