
function [ texID ] = createTex( datapath_write, name, title, startdate, starttime, enddate, endtime, gen_date, fname, bthr1, bthr2,len1, len2 )
% create the header for the tex file in a file .tex.
%
% !!! overwrite is active !!!

texID = fopen([datapath_write filesep name '.tex'], 'w+' ); 
init_str = ['\\documentclass[11pt]{article} ' '\n' ...
'\\usepackage[utf8]{inputenc} ' '\n' ...
'\\usepackage{geometry}' '\n' ...
'\\geometry{a4paper,left=3cm,right=2cm, top=2cm,bottom=2cm} ' '\n' ...
'\\usepackage{graphicx}' '\n' ...
'\\usepackage{lscape}' '\n' ...
'\n' ...
'\\title{' title '}' '\n' ...
'\\date{}' '\n' ...
'\n' ...
'\\begin{document}' '\n' ...
'\\maketitle' '\n' ...
'\\textbf{Running period:} ' num2str(startdate) ' ' starttime ' - ' num2str(enddate) ' ' endtime '\n' ...
'\n' ...
'\\textbf{Generated:} ' gen_date '\n' ...
'\n' ...
'\\textbf{Filename:} $' fname '$\n' ...
'\n' ...
'\\textbf{BPM charge tresholds:} ' '\n' ...
'\\begin{itemize}' '\n' ...
'\\item bpm1: %3.2f' '\n' ...
'\\item bpm2: %3.2f' '\n' ...
'\\end{itemize}' '\n' ...
'\n' ...
'\\textbf{Number of pulses:} ' '\n' ...
'\\begin{itemize}' '\n' ...
'\\item With beam: %3.0f' '\n' ...
'\\item Without beam: %3.0f' '\n' ...
'\\end{itemize}' '\n' ...
'\\newpage' '\n' ...
];
fprintf(texID,init_str,bthr1,bthr2,len1,len2);
fclose(texID);

end

